### ISSUE TITLE
Could you tell me more about the installation process?

### ISSUE THREAD

**Issue by 60999** [SvenKortekaas04/pico-ducky#1]
In steps 4 and 5, copy "adafruit_hid" folder to the Lib folder on the raspberry PI Pico When Pico show up as a storage device named "RPI-RP2" or "CIRCUITPY"?

I tried both places, but the script didn't work and didn't respond.

Whether the on-board led prompt can be added to check whether the script is running.

For example:

`from machine import Pin, Timer

led = Pin(25, Pin.OUT)
tim = Timer()
def tick(timer):
    global led
    led.toggle()
 
tim.init(freq=2.5, mode=Timer.PERIODIC, callback=tick)`

**Comment by SvenKortekaas04** [comment]
Hi @60999,

Out of the box, [MicroPython](https://micropython.org/) is installed on the Raspberry Pi Pico. MicroPython is a lean and efficient implementation of the [Python 3](http://www.python.org/) programming language.

Unfortunately MicroPython cannot imitate keyboard and mouse interactions. For this reason, you need to install [CircuitPython](https://circuitpython.org/board/raspberry_pi_pico/).

If you have followed the instructions correctly you have installed CircuitPython on the Raspberry Pi Pico. The Raspberry Pi Pico is now named CIRCUITPY. After you have done that, you will see a lib-folder in the root of the Raspberry Pi Pico. This is where you should put all your third-party packages, so also the [CircuitPython Libraries](https://circuitpython.org/libraries).

If you want to blink the on-board LED on the Raspberry Pi Pico, you can use this code:
```python
"""Example for Pico. Blinks the built-in LED."""
import time
import board
import digitalio

led = digitalio.DigitalInOut(board.LED)
led.direction = digitalio.Direction.OUTPUT

while True:
    led.value = not led.value
    time.sleep(0.5)
```

The code you used for blinking an LED is for MicroPython, but according to the instructions, you installed CircuitPython, which works a little differently compared to MicroPython.

For more information on getting started with the Raspberry Pi Pico click [here](https://learn.adafruit.com/getting-started-with-raspberry-pi-pico-circuitpython/blinky-and-a-button).

Hope this helps.
